apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-mainui
spec:
  replicas: 2
  selector:
    app: main
  template:
    metadata:
      name: apache
      labels:
        app: main
        rel: stable
    spec:
      containers:
      - name: httpd-container
        image: httpd:2.2
